import type { ResumeData, TemplateTheme } from '@/types';

type Props = { data: ResumeData; theme: TemplateTheme };
const Photo = ({ src }: { src?: string }) => src ? <img src={src} className="w-24 h-28 object-cover border-4 border-white shadow" /> : <div className="w-24 h-28 bg-cyan-100 border-4 border-white shadow flex items-center justify-center text-cyan-600 text-xs">PHOTO</div>;
const fragments = (t?: string) => (t || '').split(/\n|；|;/).map(v => v.trim()).filter(Boolean).slice(0, 3);

export default function TemplateCn116({ data, theme }: Props) {
  const teal = theme.colors.primary || '#17a7a6';
  const Timeline = ({ items, kind }: { items: Array<{ period: string; title: string; sub?: string; desc?: string }>; kind: string }) => <section className="mb-6"><h2 className="text-teal-700 font-black tracking-[0.18em] border-b-2 border-teal-200 pb-1 mb-3">{kind}</h2>{items.map((it, i) => <div key={i} className="grid grid-cols-[92px_20px_1fr] gap-3 mb-4"><div className="text-[11px] text-teal-700 font-bold pt-1">{it.period}</div><div className="relative"><span className="absolute left-2 top-2 bottom-[-28px] w-px bg-teal-200" /><span className="relative block w-5 h-5 rounded-full border-4 border-white shadow" style={{ backgroundColor: teal }} /></div><div><b className="text-slate-800">{it.title}</b>{it.sub && <p className="text-teal-700">{it.sub}</p>}{fragments(it.desc).map((d, j) => <p key={j}>- {d}</p>)}</div></div>)}</section>;
  return <div className="min-h-[297mm] bg-white text-[12px] text-slate-700 leading-relaxed" style={{ fontFamily: theme.font.body }}>
    <header className="relative h-40 text-white px-9 py-7 mb-8" style={{ backgroundColor: teal }}><h1 className="text-4xl font-bold tracking-[0.18em]" style={{ fontFamily: theme.font.heading }}>{data.personal.name || '姓名'}</h1><p className="mt-2 tracking-[0.32em]">TIMELINE RESUME</p><div className="mt-4 flex gap-5 text-[11px]">{[data.personal.phone, data.personal.email, data.personal.city].filter(Boolean).map((c, i) => <span key={i}>{c}</span>)}</div><div className="absolute right-10 top-8"><Photo src={data.personal.photo} /></div></header>
    <main className="px-9">{data.summary && <section className="mb-6 bg-cyan-50 p-4 border-l-4 border-teal-500"><span className="text-teal-700 font-bold">PROFILE</span><p>{data.summary}</p></section>}<Timeline kind="WORK EXPERIENCE" items={data.workExperience.map(w => ({ period: w.period, title: `${w.company} · ${w.position}`, desc: w.description }))} /><Timeline kind="PROJECT EXPERIENCE" items={data.projects.map(p => ({ period: p.period, title: p.name, sub: p.role, desc: p.description }))} /><Timeline kind="EDUCATION" items={data.education.map(e => ({ period: e.period, title: e.school, sub: `${e.major} · ${e.degree}`, desc: e.description }))} /><section><h2 className="text-teal-700 font-black tracking-[0.18em] mb-3">SKILLS</h2><div className="flex flex-wrap gap-2">{data.skills.map((s, i) => <span key={i} className="px-3 py-1 rounded-full bg-cyan-50 text-teal-700 border border-teal-200">{s.name} {s.level * 20}%</span>)}</div></section></main>
  </div>;
}
