import type { ResumeData, TemplateTheme } from '@/types';
import type { ReactNode } from 'react';

type Props = { data: ResumeData; theme: TemplateTheme };
const Photo = ({ src }: { src?: string }) => src ? <img src={src} className="w-32 h-32 rounded-full object-cover mx-auto border-4 border-stone-100" /> : <div className="w-32 h-32 rounded-full bg-stone-200 mx-auto flex items-center justify-center text-stone-500 text-xs border-4 border-stone-100">PHOTO</div>;
const bits = (t?: string) => (t || '').split(/\n|；|;/).map(x => x.trim()).filter(Boolean).slice(0, 3);

export default function TemplateCn113({ data, theme }: Props) {
  const brown = theme.colors.primary || '#8b6f4e';
  const RSection = ({ icon, title, children }: { icon: string; title: string; children: ReactNode }) => <section className="mb-5"><div className="flex items-center gap-3 mb-3"><span className="w-8 h-8 rounded-full bg-amber-100 text-stone-700 flex items-center justify-center">{icon}</span><h2 className="text-stone-700 font-black tracking-[0.16em]">{title}</h2><span className="h-px bg-amber-200 flex-1" /></div>{children}</section>;
  return <div className="min-h-[297mm] bg-white grid grid-cols-[30%_70%] text-[12px] text-stone-700 leading-relaxed" style={{ fontFamily: theme.font.body }}>
    <aside className="bg-[#e8dccb] p-7"><Photo src={data.personal.photo} /><h1 className="text-2xl font-bold text-center mt-5 tracking-widest" style={{ fontFamily: theme.font.heading, color: brown }}>{data.personal.name || '姓名'}</h1><p className="text-center text-[10px] tracking-[0.28em] mt-1">RESUME</p><div className="mt-8 space-y-5"><div><h3 className="font-bold border-b border-stone-500 pb-1 mb-2">CONTACT</h3>{[data.personal.phone, data.personal.email, data.personal.city, data.personal.website].filter(Boolean).map((c, i) => <p key={i} className="mb-1 break-all">{c}</p>)}</div><div><h3 className="font-bold border-b border-stone-500 pb-1 mb-2">SKILLS</h3>{data.skills.map((s, i) => <div key={i} className="mb-2"><span>{s.name}</span><div className="h-1.5 bg-stone-200"><div className="h-full bg-stone-600" style={{ width: `${Math.min(100, s.level * 20)}%` }} /></div></div>)}</div><div><h3 className="font-bold border-b border-stone-500 pb-1 mb-2">HOBBIES</h3><p>{(data.languages || []).map(l => `${l.language} ${l.level}`).join(' / ') || 'Reading / Travel / Music'}</p></div></div></aside>
    <main className="p-8">{data.summary && <RSection icon="人" title="PROFILE"><p>{data.summary}</p></RSection>}<RSection icon="工" title="WORK EXPERIENCE">{data.workExperience.map((w, i) => <div key={i} className="mb-4"><div className="flex justify-between font-bold text-stone-900"><span>{w.company} · {w.position}</span><span style={{ color: brown }}>{w.period}</span></div><ul className="ml-5 list-disc">{bits(w.description).map((b, j) => <li key={j}>{b}</li>)}</ul></div>)}</RSection><RSection icon="项" title="PROJECTS">{data.projects.map((p, i) => <div key={i} className="mb-3 bg-amber-50 p-3"><b>{p.name}</b> · {p.role}<p>{p.description}</p></div>)}</RSection><RSection icon="学" title="EDUCATION">{data.education.map((e, i) => <p key={i} className="mb-2"><b>{e.school}</b> / {e.major} / {e.degree}<span className="float-right">{e.period}</span></p>)}</RSection></main>
  </div>;
}
